name: Render and Publish Quarto Slides  Pages

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'slides/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: slides/whatsapp-chat.qmd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
